// src/app/layout.tsx

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { LanguageProvider } from "@/contexts/LanguageContext";
import { RegionProvider } from "@/contexts/RegionContext";
import { AuthProvider } from "@/contexts/AuthContext";
import { StructuredData } from "@/components/StructuredData";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // ✅ DEFAULT VALUES (SAFE)
  const language = "en";

  const region = {
    country: undefined,
    city: undefined,
    cinema: undefined,
  };

  return (
    <html lang={language}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StructuredData />

        <LanguageProvider initialLanguage={language}>
          <RegionProvider initialRegion={region}>
            {/* AuthProvider will fetch user from /api/auth/user */}
            <AuthProvider initialUser={null}>
              {children}
            </AuthProvider>
          </RegionProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
