import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LanguageProvider } from "@/contexts/LanguageContext";
import { RegionProvider } from "@/contexts/RegionContext";
import { AuthProvider } from "@/contexts/AuthContext";
import { getSession } from "@/lib/session";
import { StructuredData } from "@/components/StructuredData";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // getSession ab null bhi ho sakta hai, isliye optional chaining use karenge
  const session = await getSession();

  const language = session?.language ?? "en";

  const region =
    session?.region ?? {
      country: undefined,
      city: undefined,
      cinema: undefined,
    };

  const user = session?.user ?? null;

  return (
    <html lang={language}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StructuredData />
        <LanguageProvider initialLanguage={language}>
          <RegionProvider initialRegion={region}>
            <AuthProvider initialUser={user}>{children}</AuthProvider>
          </RegionProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
